import type { ComponentType } from "react";
import {
  Activity,
  AlbumCarousel,
  BadgeCheck,
  BellNotification,
  Bin,
  Book,
  BookStack,
  BookmarkBook,
  CalendarCheck,
  Camera,
  ChatBubbleQuestion,
  ChatBubble,
  Check,
  CheckCircle,
  CheckSquare,
  Clock,
  ClockRotateRight,
  Community,
  Computer,
  Compass,
  Copy,
  Drag,
  DashboardSpeed,
  DatabaseSettings,
  Download,
  EmptyPage,
  EditPencil,
  FireFlame,
  Flash,
  FilterList,
  GraphUp,
  HalfMoon,
  HeadsetHelp,
  Home,
  JournalPage,
  Label,
  LeaderboardStar,
  List,
  Lock,
  LogOut,
  Mail,
  MoreHoriz,
  MapPin,
  Medal,
  Medal1st,
  MessageText,
  MultiplePagesPlus,
  NavArrowDown,
  NavArrowLeft,
  NavArrowRight,
  NavArrowUp,
  OpenBook,
  Page,
  PageRight,
  Palette,
  Pause,
  Play,
  Plus,
  PrivacyPolicy,
  Reports,
  Refresh,
  ScanBarcode,
  Search,
  Send,
  Settings,
  ShareIos,
  ShieldCheck,
  ShieldEye,
  ShieldPlusIn,
  Sparks,
  Star,
  StatsReport,
  Suggestion,
  SunLight,
  Square,
  Text as TextIcon,
  Timer,
  Trash,
  TriangleFlag,
  User,
  UserBadgeCheck,
  UserCircle,
  UserPlus,
  UserSquare,
  ViewGrid,
  ViewStructureUp,
  WarningTriangle,
  Xmark,
} from "iconoir-react";

export type AppIcon = ComponentType<{ className?: string }>;

export const APP_ICONS = {
  nav: {
    home: Home,
    library: OpenBook,
    lists: List,
    analytics: StatsReport,
    goals: TriangleFlag,
    achievements: LeaderboardStar,
    feed: Activity,
    readers: User,
    clubs: Community,
    messages: MessageText,
    reviews: Star,
    settings: Settings,
  },
  settings: {
    account: Lock,
    profile: UserCircle,
    personal: UserSquare,
    app: Palette,
    notifications: BellNotification,
    privacy: PrivacyPolicy,
    support: HeadsetHelp,
    readingProfile: BookStack,
    dataBackup: Download,
    profileVisibility: ShieldEye,
    dataSharing: DatabaseSettings,
    faq: ChatBubbleQuestion,
    contact: Mail,
    feedback: Suggestion,
    sendMessage: MessageText,
  },
  dashboard: {
    continueReading: PageRight,
    today: CalendarCheck,
    goal: TriangleFlag,
    streak: FireFlame,
    insights: Reports,
    recentActivity: ClockRotateRight,
    emptyWithBooks: BookStack,
    emptyNoBooks: EmptyPage,
    coverFallback: OpenBook,
  },
  library: {
    bookLists: BookmarkBook,
    analytics: GraphUp,
    addBook: MultiplePagesPlus,
    emptyResults: EmptyPage,
    filter: FilterList,
    flatView: ViewGrid,
    bookshelfView: ViewStructureUp,
    carouselView: AlbumCarousel,
  },
  analytics: {
    header: StatsReport,
    completed: BadgeCheck,
    readingTime: Clock,
    dailyAverage: DashboardSpeed,
    favoriteGenre: Label,
    empty: Reports,
  },
  readers: {
    readers: User,
    clubs: Community,
    all: Sparks,
    suggestions: Sparks,
    nearby: MapPin,
    connections: UserPlus,
    friendsOfFriends: Community,
    similarTaste: Book,
    active: Activity,
    myClubs: UserBadgeCheck,
    discoverClubs: Compass,
    booksRead: Book,
    streak: FireFlame,
    distance: MapPin,
  },
  profile: {
    social: UserCircle,
    picture: UserSquare,
    followers: UserPlus,
    following: UserBadgeCheck,
    totalBooks: BookStack,
    booksRead: BadgeCheck,
    streak: FireFlame,
    badges: Medal,
    posts: MessageText,
    clubs: Community,
    edit: Settings,
    message: MessageText,
    joined: CalendarCheck,
    booksTab: OpenBook,
  },
  bookDetail: {
    startTimer: Timer,
    logProgress: JournalPage,
    detailedAnalytics: GraphUp,
    description: TextIcon,
    recentSessions: ClockRotateRight,
    progressEmpty: Reports,
    progressDate: CalendarCheck,
  },
  stats: {
    header: Reports,
    library: BookStack,
    completed: BadgeCheck,
    streak: FireFlame,
    readingTime: Clock,
    pagesRead: Page,
    pace: Flash,
    longestBook: OpenBook,
    longestStreak: LeaderboardStar,
    freezeStatus: ShieldCheck,
    useFreeze: ShieldPlusIn,
  },
  journey: {
    overview: Sparks,
    quests: CalendarCheck,
    badges: Medal1st,
    rankings: LeaderboardStar,
    ink: EditPencil,
    goldLeaf: Sparks,
  },
  badges: {
    collection: BookStack,
    completion: BadgeCheck,
    streak: FireFlame,
    time: Clock,
    pages: Page,
    exploration: Compass,
    craft: EditPencil,
    journey: Medal1st,
    book: Book,
    bookStack: BookStack,
    bookshelf: BookmarkBook,
    library: OpenBook,
    bookmarkBook: BookmarkBook,
    badgeCheck: BadgeCheck,
    checkCircle: CheckCircle,
    openBook: OpenBook,
    medal: Medal,
    medalFirst: Medal1st,
    trophy: LeaderboardStar,
    fire: FireFlame,
    calendarCheck: CalendarCheck,
    leaderboardStar: LeaderboardStar,
    clock: Clock,
    timer: Timer,
    hourglass: Timer,
    sunrise: SunLight,
    moon: HalfMoon,
    page: Page,
    pageRight: PageRight,
    multiplePages: MultiplePagesPlus,
    compass: Compass,
    map: MapPin,
    user: User,
    community: Community,
    flash: Flash,
    list: List,
    star: Star,
    reports: Reports,
    flag: TriangleFlag,
    target: TriangleFlag,
    spark: Sparks,
    leaderboard: LeaderboardStar,
  },
  floatingAction: {
    quickStats: Reports,
    timer: Timer,
    addBook: MultiplePagesPlus,
    scanBarcode: ScanBarcode,
    scanCover: Camera,
    search: Search,
    history: ClockRotateRight,
    bookFallback: OpenBook,
  },
  common: {
    add: Plus,
    back: NavArrowLeft,
    chat: ChatBubble,
    check: Check,
    checkCircle: CheckCircle,
    close: Xmark,
    collapse: NavArrowDown,
    copy: Copy,
    search: Search,
    camera: Camera,
    delete: Trash,
    drag: Drag,
    edit: EditPencil,
    forward: NavArrowRight,
    media: Camera,
    pause: Pause,
    play: Play,
    refresh: Refresh,
    select: CheckSquare,
    send: Send,
    share: ShareIos,
    stop: Square,
    themeDark: HalfMoon,
    themeLight: SunLight,
    themeSystem: Computer,
    up: NavArrowUp,
    warning: WarningTriangle,
    download: Download,
    clearCache: Bin,
    deleteItem: Trash,
    more: MoreHoriz,
    signOut: LogOut,
  },
} as const;
