import type { ComponentType } from "react";
import {
  Activity,
  BadgeCheck,
  BellNotification,
  Bin,
  Book,
  BookStack,
  BookmarkBook,
  CalendarCheck,
  Camera,
  ChatBubbleQuestion,
  Clock,
  ClockRotateRight,
  Community,
  Compass,
  DashboardSpeed,
  DatabaseSettings,
  Download,
  EmptyPage,
  FireFlame,
  Flash,
  FilterList,
  GraphUp,
  HeadsetHelp,
  Home,
  JournalPage,
  Label,
  LeaderboardStar,
  List,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Medal,
  Medal1st,
  MessageText,
  MultiplePagesPlus,
  OpenBook,
  Page,
  PageRight,
  Palette,
  PrivacyPolicy,
  Reports,
  ScanBarcode,
  Search,
  Settings,
  ShieldCheck,
  ShieldEye,
  ShieldPlusIn,
  Sparks,
  Star,
  StatsReport,
  Suggestion,
  Text as TextIcon,
  Timer,
  Trash,
  TriangleFlag,
  User,
  UserBadgeCheck,
  UserCircle,
  UserPlus,
  UserSquare,
} from "iconoir-react";

export type AppIcon = ComponentType<{ className?: string }>;

export const APP_ICONS = {
  nav: {
    home: Home,
    library: OpenBook,
    lists: List,
    analytics: StatsReport,
    goals: TriangleFlag,
    achievements: Medal1st,
    feed: Activity,
    readers: User,
    clubs: Community,
    messages: MessageText,
    reviews: Star,
    settings: Settings,
  },
  settings: {
    account: Lock,
    profile: UserCircle,
    personal: UserSquare,
    app: Palette,
    notifications: BellNotification,
    privacy: PrivacyPolicy,
    support: HeadsetHelp,
    readingProfile: BookStack,
    profileVisibility: ShieldEye,
    dataSharing: DatabaseSettings,
    faq: ChatBubbleQuestion,
    contact: Mail,
    feedback: Suggestion,
    sendMessage: MessageText,
  },
  dashboard: {
    continueReading: PageRight,
    today: CalendarCheck,
    goal: TriangleFlag,
    streak: FireFlame,
    insights: Reports,
    recentActivity: ClockRotateRight,
    emptyWithBooks: BookStack,
    emptyNoBooks: EmptyPage,
    coverFallback: OpenBook,
  },
  library: {
    bookLists: BookmarkBook,
    analytics: GraphUp,
    addBook: MultiplePagesPlus,
    emptyResults: EmptyPage,
    filter: FilterList,
  },
  analytics: {
    header: StatsReport,
    completed: BadgeCheck,
    readingTime: Clock,
    dailyAverage: DashboardSpeed,
    favoriteGenre: Label,
    empty: Reports,
  },
  readers: {
    readers: User,
    clubs: Community,
    all: Sparks,
    nearby: MapPin,
    connections: UserPlus,
    similarTaste: Book,
    active: Activity,
    myClubs: UserBadgeCheck,
    discoverClubs: Compass,
    booksRead: Book,
    streak: FireFlame,
    distance: MapPin,
  },
  profile: {
    social: UserCircle,
    picture: UserSquare,
    followers: UserPlus,
    following: UserBadgeCheck,
    totalBooks: BookStack,
    booksRead: BadgeCheck,
    streak: FireFlame,
    badges: Medal,
    posts: MessageText,
    clubs: Community,
    edit: Settings,
    message: MessageText,
    joined: CalendarCheck,
    booksTab: OpenBook,
  },
  bookDetail: {
    startTimer: Timer,
    logProgress: JournalPage,
    detailedAnalytics: GraphUp,
    description: TextIcon,
    recentSessions: ClockRotateRight,
    progressEmpty: Reports,
    progressDate: CalendarCheck,
  },
  stats: {
    header: Reports,
    library: BookStack,
    completed: BadgeCheck,
    streak: FireFlame,
    readingTime: Clock,
    pagesRead: Page,
    pace: Flash,
    longestBook: OpenBook,
    longestStreak: LeaderboardStar,
    freezeStatus: ShieldCheck,
    useFreeze: ShieldPlusIn,
  },
  floatingAction: {
    quickStats: Reports,
    timer: Timer,
    addBook: MultiplePagesPlus,
    scanBarcode: ScanBarcode,
    scanCover: Camera,
    search: Search,
    history: ClockRotateRight,
    bookFallback: OpenBook,
  },
  common: {
    search: Search,
    camera: Camera,
    download: Download,
    clearCache: Bin,
    deleteItem: Trash,
    signOut: LogOut,
  },
} as const;
