// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://waftnaqgkcgufzapcihe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhZnRuYXFna2NndWZ6YXBjaWhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5Njk1MjQsImV4cCI6MjA2OTU0NTUyNH0.fZadW4MHqX4pQmJnElNb5fr-HRcT8pIi0sAOzsoQu2E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});